Update generate script (syncqt.pl -> syncqt.cpp)

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -220,12 +220,6 @@ function symlink_source_file () # <symlink-target-path> <destination-dir-path>
   #
   local dt="${ut/upstream/downstream}" # Downstream symlink target path.
 
-  # Skip QtGui's QPA headers (they get special treatment later).
-  #
-  if [[ "$ut" == */gui/*/qplatform*.h ]]; then
-    return
-  fi
-
   # If a downstream version was not found, try again with a .in extension.
   #
   if [[ ! -f "$d/$dt" ]]; then
@@ -289,6 +283,12 @@ function symlink_non_module () # <source-directory> <destination-directory>
   done
 }
 
+# Regexes which identify QPA and RHI headers. Taken from
+# upstream/qtbase/src/gui/CMakeLists.txt.
+#
+qpa_re='(^|/)qplatform.+\.h$|(^|/)qwindowsystem.+\.h$'
+rhi_re='(^|/)qrhi\.h$|(^|/)qrhi_platform\.h$|(^|/)qshader\.h$|(^|/)qshaderdescription\.h$'
+
 # Symlink all of the sources and other files of interest in the upstream Qt
 # module subdirectory <subdir> into <output-path-prefix>/<module-name>/,
 # preserving subdirectories.
@@ -327,9 +327,11 @@ function symlink_non_module () # <source-directory> <destination-directory>
 #        │   ├── bar.cpp
 #        │   ...
 #        ├── private
-#        │   ├── foo_p.h
-#        │   ├── bar_p.h
-#        │   ...
+#        │   └── QtModuleName
+#        │       └── private
+#        │           ├── foo_p.h
+#        │           ├── bar_p.h
+#        │           ...
 #        ├── foo.h
 #        ├── bar.h
 #        ...
@@ -371,6 +373,12 @@ function symlink_module_subdir () # <output-path-prefix> <module-name> <subdir>
   for f in "$sd"/*; do
     tpp= # Target path prefix.
     spp= # Symlink path prefix.
+
+    # Skip QPA and RHI headers (they get special treatment later).
+    #
+    if [[ "$f" =~ $qpa_re || "$f" =~ $rhi_re ]]; then
+      continue
+    fi
 
     case "$f" in
       # Private header.
@@ -597,177 +605,261 @@ echo '#include "qcoreapplication.h"' > Qt6Uic/uic/QtCore/QCoreApplication
 #
 echo '#include <private/qtrace_p.h>' > libQt6Core/QtCore/qtcore_tracepoints_p.h
 
-# Copy headers generated by the upstream build into libQt6Core/QtCore/. (None
-# of these are required for the Qt6Moc build.)
+# Extract the Qt version from upstream/qtbase/.cmake.conf and break it down
+# into its components.
 #
-# The majority of the generated headers are camelcase versions of the public
-# headers (foobar.h -> QFooBar) but a few additional headers (public only) are
-# also generated.
+# Format: <major>.<minor>.<patch>
 #
-# Run the upstream syncqt.pl script to produce the include tree and copy only
-# those headers that don't also exist in the upstream directory (in which case
-# they are not generated and will already have been symlinked above).
+# For reference, in our buildfiles we do:
 #
+#  QT_VERSION_STR="$version.major.$version.minor.$version.patch"
+#  QT_VERSION_MAJOR="$version.major"
+#  QT_VERSION_MINOR="$version.minor"
+#  QT_VERSION_PATCH="$version.patch"
+#
+qt_version_str="$(sed -nE 's%^\s*set\(QT_REPO_MODULE_VERSION "(.+)"\)%\1%p' \
+                      upstream/qtbase/.cmake.conf)"
 
-# Extract the Qt version from upstream/qtbase/.cmake.conf.
-#
-qt_version="$(sed -nE 's%set\(QT_REPO_MODULE_VERSION "(.+)"\)%\1%p' \
-                  upstream/qtbase/.cmake.conf)"
+if [[ -z "$qt_version_str" ]]; then
+  error "failed to extract Qt version"
+fi
 
-# Copy headers generated by the upstream build.
+if [[ "$qt_version_str" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+  qt_version_major="${BASH_REMATCH[1]}"
+  qt_version_minor="${BASH_REMATCH[2]}"
+  qt_version_patch="${BASH_REMATCH[3]}"
+else
+  error "failed to parse extracted Qt version"
+fi
+
+# Compile the syncqt tool.
 #
-# The majority of the generated headers are camelcase versions of the public
+c++ -DQT_VERSION_MAJOR=$qt_version_major \
+    -DQT_VERSION_MINOR=$qt_version_minor \
+    -DQT_VERSION_PATCH=$qt_version_patch \
+    -DQT_VERSION_STR="\"$qt_version_str\"" \
+    -o syncqt \
+    upstream/qtbase/src/tools/syncqt/main.cpp
+
+# Generate headers for a Qt module into a temporary directory and copy them
+# into our source tree.
+#
+# In the upstream build the syncqt tool copies and/or transforms headers from
+# the source directory tree into a separate include directory tree. The
+# majority of the transformed headers are camelcase versions of the public
 # headers (foobar.h -> QFooBar) but in some cases headers from different
-# subdirectories are copied to a single directory to allow their inclusion
-# using a common path prefix.
+# subdirectories are placed in a single directory to allow their inclusion
+# using a common path prefix (e.g., QPA/RHI headers). A few headers are also
+# generated from other types of inputs.
 #
-# Run the upstream syncqt.pl script to produce the include tree and copy only
-# those headers that don't already exist in the upstream directory (in which
-# case they are not generated and will already have been symlinked above).
+# <module-name>: One of QtCore, QtGui, or QtWidgets.
 #
-
-# Run the upstream syncqt.pl script to generate headers for the given Qt
-# module in a temporary directory.
+# <upstream-src-dir>: The module's upstream directory under
+# upstream/qtbase/src/.
 #
-# Return the path to the temporary directory.
+# <known-modules>: The names of all of the Qt modules (minus the "Qt" prefix)
+# this module may include headers from (including itself).
 #
-function gen_hdrs () # <module-name>
+# Run syncqt (compiled from upstream sources above) to produce their include
+# tree in a temporary directory and copy only those headers that don't already
+# exist in our source tree (in which case they are not generated or moved by
+# syncqt and will thus already have been symlinked above). Also move the
+# private QPA/RHI headers into the private header directory (upstream mixes
+# public and private headers in these subdirectories for some reason).
+#
+# Note that we completely ignore the regular (non-QPA/RHI) private headers
+# output by syncqt because those are just copied (not transformed or moved)
+# and we have already symlinked them into place above.
+#
+function gen_hdrs () # <module-name> <upstream-src-dir> <known-modules>
 {
-  local mod="$1" # Module name.
+  local mod="$1"        # Module name (QtCore, QtGui, QtWidgets).
+  local srcdir="$2"     # Upstream source directory.
+  local known_mods="$3" # Known Qt modules.
+
+  # The list of public and private module headers to be passed to syncqt.
+  #
+  # Note that we cannot simply omit the headers we've already symlinked above
+  # (in order to prevent overwrites) because syncqt creates multiple outputs
+  # from some headers (for example, it copies and produces CamelCase versions
+  # of public headers).
+  #
+  local hdrs=()
+
+  # Search for upstream headers, skipping the doc directory.
+  #
+  local d # Directory
+  for d in "$PWD/upstream/qtbase/src/$srcdir/"*/; do
+    if [[ "$(basename "$d")" == "doc" ]]; then
+      continue
+    fi
+
+    hdrs+=($(find "$d" -name \*.h))
+  done
+
+  # Temporary output directory into which to generate the headers.
+  #
   local tmpdir
   if ! tmpdir="$(mktemp -d)"; then
     error "mktemp failed"
   fi
 
-  if ! upstream/qtbase/libexec/syncqt.pl           \
-       -copy -module "$mod" -version "$qt_version" \
-       -outdir "$tmpdir" upstream/qtbase           \
-       > /dev/null; then
-    rm -r "$tmpdir"
-    error "syncqt.pl failed"
+  # A temporary directory to use for syncqt's `binaryDir` argument (the
+  # module's build directory).
+  #
+  # In addition to configure time, the upstream build also runs syncqt at
+  # build time if any module headers have changed, in which case it may
+  # process headers in the module's build directory. syncqt also outputs to
+  # this directory a header exclusion list used by a separate header-checking
+  # target (QtHeadersClean.cmake) of the upstream build.
+  #
+  # Because none of these cases apply to us it's safe to pass a temporary
+  # directory instead.
+  #
+  local bindir
+  if ! bindir="$(mktemp -d)"; then
+    error "mktemp failed"
   fi
 
-  echo "$tmpdir"
+  # Temporary directory used by syncqt.
+  #
+  local staging_dir
+  if ! staging_dir="$(mktemp -d)"; then
+    error "mktemp failed"
+  fi
+
+  # Run syncqt.
+  #
+  # Arrange for the output tree to resemble our source tree as far as possible
+  # (see symlink_module_subdir() above for reference):
+  #
+  #   <tmpdir>
+  #   ├─ private
+  #   │  └─ QtModuleName
+  #   │      └─ private
+  #   │         ├─ foo_p.h
+  #   │         ├─ bar_p.h
+  #   │         ...
+  #   ├─ qpa
+  #   │  ├─ foo.h
+  #   │  ├─ foo_p.h
+  #   │  ...
+  #   └─ rhi
+  #      ├─ foo.h
+  #      ├─ foo_p.h
+  #      ...
+  #
+  # See upsteam/qtbase/src/tools/syncqt/main.cpp for a description of the
+  # options.
+  #
+  # In the upstream build the arguments for the QtCore module, for example,
+  # can be found in <upstream-build-dir>/src/corelib/Core_syncqt_args.
+  #
+  # -copy:         Copy instead of symlink the source headers.
+  # -sourceDir:    Module source directory.
+  # -binaryDir:    Module build directory (see above).
+  # -includeDir:   The public header output directory.
+  # -*IncludeDir:  Output directories for the other kinds of headers.
+  # -knownModules: Other Qt modules this module might include headers from.
+  # -stagingDir:   Temporary directory used by syncqt (see above).
+  # -headers:      List of headers to process.
+  #
+  # Note that SSG headers only exist in the QtQuick3D module so the
+  # `-ssgIncludeDir` does not matter despite being a required option.
+  #
+  if ! ./syncqt                                      \
+       -module "$mod"                                \
+       -copy                                         \
+       -sourceDir "$PWD/upstream/qtbase/src/$srcdir" \
+       -binaryDir "$bindir"                          \
+       -includeDir "$tmpdir"                         \
+       -privateIncludeDir "$tmpdir/private"          \
+       -privateHeadersFilter '.+_p(ch)?\.h'          \
+       -qpaIncludeDir "$tmpdir/qpa"                  \
+       -qpaHeadersFilter $qpa_re                     \
+       -rhiIncludeDir "$tmpdir/rhi"                  \
+       -rhiHeadersFilter $rhi_re                     \
+       -ssgIncludeDir "$tmpdir/ssg"                  \
+       -knownModules "$known_mods"                   \
+       -stagingDir "$staging_dir"                    \
+       -headers "${hdrs[@]}"                         \
+       > /dev/null; then
+    rm -r "$staging_dir" "$bindir" "$tmpdir"
+    error "syncqt failed"
+  fi
+
+  # The module's public header directory in our source tree.
+  #
+  # For example: libQt6Core/QtCore
+  #
+  local outdir="libQt6${mod#Qt}/$mod"
+
+  # Copy headers from the temporary syncqt output directory into `outdir`.
+  #
+  # Note that we do not descend into private/ because (non-QPA/RHI) private
+  # headers have already been handled (see above).
+  #
+  # @@ TMP This has been moved into this function because syncqt.cpp requires
+  #        the QPA/RHI directory arguments for all modules so presumably
+  #        e.g. QtWidgets could someday have QPA/RHI headers too. So handle
+  #        all modules the same (just like syncqt now does).
+  #
+  local p # Path (file or directory)
+  for p in "$tmpdir"/*; do
+    local fn="$(basename "$p")" # Filename
+
+    if [[ ("$fn" == *.h && ! -e "$outdir/$fn") || "$fn" == Q* ]]; then
+      # Non-QPA/RHI public headers (qfoo_bar.h or QFooBar).
+      #
+      cp "$p" "$outdir/"
+    elif [[ "$fn" == "qpa" || "$fn" == "rhi" ]]; then
+      # Handle QPA/RHI subdirectories.
+      #
+      local sd="$fn" # Subdirectory name.
+
+      local up # Upstream file path.
+      for up in "$p"/*; do
+        local dd # Destination directory path
+        case "$up" in
+          *_p.h) dd="$outdir/private/$mod/$sd" ;;
+          *.h)   dd="$outdir/$sd"              ;;
+          *)     continue                      ;; # Skip non-headers.
+        esac
+
+        fn="$(basename "$up")" # Filename
+
+        # Downstream file path, if there is a patched version. We have to run
+        # find because the upstream build copies the QPA/RHI headers from
+        # various source code subdirectories.
+        #
+        local dp="$(find "downstream/qtbase/src/$srcdir/" -name "$fn")"
+
+        # If a downstream copy exists, copy it to the destination directory
+        # along with the original (generated by the upstream build) which gets
+        # a '.orig' suffix. Otherwise just copy the original (without
+        # suffix). NOTE: a similar scheme is implemented in
+        # symlink_source_file() above.
+        #
+        if [[ -n "$dp" ]]; then
+          cp "$dp" "$dd/$fn"
+          cp "$up" "$dd/$fn.orig"
+        else
+          cp "$up" "$dd/$fn"
+        fi
+      done
+    fi
+  done
+
+  rm -r "$staging_dir" "$bindir" "$tmpdir"
 }
 
-# Copy headers generated for QtCore into libQt6Core/QtCore/.
-#
-tmpdir="$(gen_hdrs QtCore)"
+gen_hdrs QtCore    corelib "Core"
+gen_hdrs QtGui     gui     "Core Gui"
+gen_hdrs QtWidgets widgets "Core Gui Widgets"
 
-# Copy those public *.h headers that have not already been symlinked and all
-# camelcase headers (of which all are generated and thus none symlinked).
+# The Qt*Depends headers are generated by cmake in the upstream build.
 #
-for p in "$tmpdir/include/QtCore/"*; do
-  f="$(basename "$p")"
-  if [[ ("$f" == *.h && ! -e "libQt6Core/QtCore/$f") || "$f" == Q* ]]; then
-    cp "$p" libQt6Core/QtCore/
-  fi
-done
-
-rm -r "$tmpdir"
-
-# This (empty) header is generated by qmake in the upstream build.
-#
-touch libQt6Core/QtCore/QtCoreDepends
-
-# syncqt.pl does not create QOperatingSystemVersion whereas syncqt.cpp does.
-#
-# @@ TMP see TODO about syncqt.cpp below.
-#
-# @@ TMP The qt_class pragma instances in
-#        corelib/global/qoperatingsystemversion.h are what cause these headers
-#        to be generated.
-#
-cp libQt6Core/QtCore/QOperatingSystemVersionBase \
-   libQt6Core/QtCore/QOperatingSystemVersion
-
-# Copy headers generated for QtGui into libQt6Gui/QtGui/.
-#
-tmpdir="$(gen_hdrs QtGui)"
-
-# In addition to the generated public *.h and Q* headers as for QtCore, also
-# copy the generated QPA (Qt Platform Abstraction) headers.
-#
-# Note that they are usually included with a `qpa/` prefix so must go into
-# their own subdirectory (unlike normal headers).
-#
-for p in "$tmpdir/include/QtGui/"*; do
-  f="$(basename "$p")" # Filename
-
-  if [[ ("$f" == *.h && ! -e "libQt6Gui/QtGui/$f") || "$f" == Q* ]]; then
-    # We have a generated non-QPA header (qfoo_bar.h or QFooBar).
-    #
-    cp "$p" libQt6Gui/QtGui/
-  elif [[ "$f" == "$qt_version" ]]; then
-    for up in "$p/QtGui/qpa/"*; do # up: upstream file path
-      # We have a generated QPA header.
-      #
-      f="$(basename "$up")" # Filename
-
-      d=                    # Destination directory path
-      case "$up" in
-        *_p.h) d=libQt6Gui/QtGui/private/QtGui/qpa ;;
-          *.h) d=libQt6Gui/QtGui/qpa               ;;
-      esac
-
-      # Downstream file path, if there is a patched version. The upstream
-      # build copies the QPA headers from various subdirectories of
-      # upstream/qtbase/src/gui/ so we have to run find.
-      #
-      dp="$(find downstream/qtbase/src/gui/ -name "$f")"
-
-      # If a downstream copy exists, copy it to the destination directory
-      # along with the original (generated by the upstream build) which gets a
-      # '.orig' suffix. Otherwise just copy the original (without
-      # suffix). NOTE: a similar scheme is implemented in
-      # symlink_source_file() above.
-      #
-      if [[ -n "$dp" ]]; then
-        cp "$dp" "$d/$f"
-        cp "$up" "$d/$f.orig"
-      else
-        cp "$up" "$d/$f"
-      fi
-    done
-  fi
-done
-
-rm -r "$tmpdir"
-
-# Move the QtGui RHI headers into place.
-#
-# Note that unlike the QPA headers these are not collected and arranged by the
-# syncqt.pl script so the source files are the symlinks we created above in
-# libQt6Gui/.
-#
-# @@ TODO Upstream is in the process of moving from syncqt.pl to
-#         syncqt.cpp. QtGui has already made the move so upstream the RHI
-#         headers are handled just like the QPA ones. syncqt.pl, which we use,
-#         does not handle the RHI headers so we have to do it manually.
-#         Currently this is not too hard because there are few RHI headers and
-#         they're all in the same directory. But we should probably make the
-#         move to syncqt.cpp.
-#
-# Note that downstream patches, if any, have already been applied.
-#
-rhi_hdr=(libQt6Gui/QtGui/qrhi.h
-         libQt6Gui/QtGui/qrhi_platform.h
-         libQt6Gui/QtGui/qshader.h
-         libQt6Gui/QtGui/qshaderdescription.h)
-
-# Note: mv would most likely break the symlinks so use cp and rm instead.
-#
-cp -H "${rhi_hdr[@]}" "libQt6Gui/QtGui/rhi"
-rm "${rhi_hdr[@]}"
-
-# Remove inclusion of the RHI headers from the QtGui header. syncqt.cpp does
-# not include any RHI headers from the QtGui header but syncqt.pl does so
-# until we upgrade we'll have to remove them.
-#
-for h in "${rhi_hdr[@]}"; do
-  h="$(basename "$h")"
-  sed -i "/#include \"$h\"/d" libQt6Gui/QtGui/QtGui
-done
+touch libQt6Core/QtCore/QtCoreDepends # Empty in QtCore's case.
 
 cat > libQt6Gui/QtGui/QtGuiDepends << EOF
 /* This file was generated by the generate script in the build2 amalgamation
@@ -778,20 +870,6 @@ cat > libQt6Gui/QtGui/QtGuiDepends << EOF
 #  include <QtCore/QtCore>
 #endif
 EOF
-
-# Copy headers generated for QtWidgets into libQt6Widgets/QtWidgets/.
-#
-tmpdir="$(gen_hdrs QtWidgets)"
-
-for p in "$tmpdir/include/QtWidgets/"*; do
-  f="$(basename "$p")"
-
-  if [[ ("$f" == *.h && ! -e "libQt6Widgets/QtWidgets/$f") || "$f" == Q* ]]; then
-    cp "$p" libQt6Widgets/QtWidgets/
-  fi
-done
-
-rm -r "$tmpdir"
 
 cat > libQt6Widgets/QtWidgets/QtWidgetsDepends << EOF
 /* This file was generated by the generate script in the build2 amalgamation
